server:
  port: 8082

spring:

  application:
    name: storage-service

  profiles:
    active: dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/seata_account?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
      username: root
      password:

  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000

mybatis:
  mapperLocations: classpath:mappers/*.xml
  typeAliasesPackage: com.xjc.seatasaga.storage.mapper.dataobject