server:
  port: 8080

spring:

  application:
    name: account-service

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/seata_account?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password:

  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000

mybatis:
  mapperLocations: classpath:mappers/*.xml
  typeAliasesPackage: com.xjc.seatasaga.account.mapper.dataobject